name: edgedb
description: Dart client library for EdgeDB
version: 0.0.1
homepage: https://www.edgedb.com

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crypto: ^3.0.2
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
